### PR TITLE
[PR] project file cleanup

### PR DESCRIPTION
**Pull request by jakubmisek**
thanks for the project in the first place! 

this PR cleanups the project files according to best practices we have; also it fixes a few Content/None/Compile mismatches in the project file.

- updated to peachpie preview2, create a common props file
- content files are moved back to mantisBT project folder
- corrected build items (updated Compile items, updated Content items)
- excluded /tests/ from the compilation

### CODE REVIEW

**Comment by jakubmisek** [comment]
@zewar96 after running `composer install` I have a few warnings about really old deprecated packages.

When trying to build the project, it fails with a missing class. It seems `adodb-php` package has a missing file `\vendor\adodb\adodb-php\pear\Auth\Container\Container.php`

**Comment by zewar96** [comment]
Thank you so much for taking the time to help me learn this!  I will definitely try to continue this exercise to see if I can get it working as hopefully help you guys advance PeachPie.

**Comment by jakubmisek** [comment]
It would be great to make this working!

So far I tried the initial installation page. Will try to advance.

I haven't had the problem with local variables tho yet.

**Comment by zewar96** [comment]
I am able to get to the installation page as well, but when i try to do anything, ADO functions are missing.  This is probably because of your previous comment of it being old/deprecated.

When i debug this within VS 2019, anything I do to look at $_SERVER (where it's $_SERVER or _SERVER or SERVER) it says that it does not exist ni the current context.

Is this because it's global?  Is there another way I can access it?

**Comment by jakubmisek** [comment]
you have to call `composer install` first. The project has composer dependencies that have to be installed first.

**Comment by zewar96** [comment]
How did you get around the Auth_Container could not be resolved issue?

**Comment by jakubmisek** [comment]
@zewar96 I didn't - seems the package requirement in `composer.json` is just wrong, and the specified version of the package is missing this file: `\vendor\adodb\adodb-php\pear\Auth\Container\Container.php`.

**Comment by zewar96** [comment]
Very interesting.  Where did you find the file?  I went to https://github.com/ADOdb/ADOdb/tree/v5.20.18/pear/Auth and i don't see that file in there.

**Comment by jakubmisek** [comment]
@zewar96 hmm, I just see they try to include that file at https://github.com/ADOdb/ADOdb/blob/0363eca78eed8bd02d1456072c729da302655241/pear/Auth/Container/ADOdb.php#L17

```php
require_once 'Auth/Container.php';
```

**Comment by zewar96** [comment]
@jakubmisek If i had to guess, i would assume that I need to include https://packagist.org/packages/pear/auth in to my composer information.  Thoughts?

**Pull request merged**
